### ISSUE TITLE
Is there any open source licensing for this repo

### ISSUE THREAD

**Issue by ridhwankamil** [manishsaroya/GNG#1]
Hello @manishsaroya correct me if im wrong, 
im kind of new on this kind open source repo, 
i suppose if i want to use the code on the repo, it needs to have valid/proper detail licensing.
So i would like to use some of the code from this repo but i can't find license detail.
Is it okay if i use some of the code for academic purpose.

**Comment by manishsaroya** [comment]
I think that's fine, you can use it for academic purpose
